version: "3.10"
services:
  hangman-app:
    container_name: app-hangman-app
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - database
    environment:
      - SERVER_HOST=https://localhost
      - PROJECT_NAME=hangman_app
      - SQLALCHEMY_MAX_POOL_OVERFLOW=20
    ports:
      - "5002:5002"
    volumes:
      - ../hangman_project:/usr/src/app/
      - ../logs:/usr/src/app/logs
      - ../hangman_project/logging_config.ini:/usr/src/app/logging_config.ini

    networks:
      - development
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - hangman-app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/proxy_params:/etc/nginx/proxy_params:ro
    networks:
      - development
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:
      - CERTBOT_EMAIL=Danielius.au@gmail.com
    command: certonly --webroot --webroot-path=/var/www/certbot -d eviteja.lt -d www.eviteja.lt
    depends_on:
      - nginx
  database:
    container_name: postgresql_hangman
    image: postgres:15

    volumes:
      - postgre:/var/lib/postgresql/data
    networks:
      - development
    ports:
      - "5432:5432"

networks:
  development:


volumes:
  postgre: