version: "3.10"
services:
  hangman-app:
    container_name: app-hangman-app
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - database
    environment:
      - SERVER_HOST=https://localhost
      - PROJECT_NAME=hangman_app
      - SQLALCHEMY_MAX_POOL_OVERFLOW=20
    ports:
      - "5002:5002"
    volumes:
      - ../hangman_project:/usr/src/app/
      - C:/Code/baigiamas_hangman/logs:/usr/src/app/logs
      - C:/Code/baigiamas_hangman/hangman_project/logging_config.ini:/usr/src/app/logging_config.ini

    networks:
      - development
 

  database:
    container_name: postgresql_hangman
    image: postgres:15

    volumes:
      - postgre:/var/lib/postgresql/data
    networks:
      - development
    ports:
      - "5432:5432"

networks:
  development:


volumes:
  postgre: